name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_arm_cross:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get update && sudo apt-get -y install g++-arm-linux-gnueabihf --fix-missing

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="arm-linux-gnueabihf-g++" -DSIMD_TARGET="arm"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

  build_aarch64_cross:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get update && sudo apt-get -y install g++-aarch64-linux-gnu --fix-missing

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="aarch64-linux-gnu-g++" -DSIMD_TARGET="aarch64"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

  build_and_test_clang:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get update && sudo apt-get -y install clang

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="clang" -DSIMD_TARGET="" -DSIMD_TEST_FLAGS="-march=native"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./Test "-r=.." -m=a -tt=$(nproc) "-ot=log_${{matrix.build_type}}.txt" -ts=10

  build_and_test_gcc_old:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        gcc_version: [10, 11]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get update && sudo apt-get -y install g++-${{matrix.gcc_version}}

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="g++-${{matrix.gcc_version}}" -DSIMD_TARGET="" -DSIMD_AVX512VNNI=ON -DSIMD_AVX512BF16=ON -DSIMD_AMXBF16=ON -DSIMD_TEST_FLAGS="-march=native"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./Test "-r=.." -m=a -tt=$(nproc) "-ot=log_${{matrix.build_type}}.txt" -ts=10

  build_and_test_gcc_new:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        gcc_version: [13]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Host properties
      run: lscpu

    - name: Install toolchain
      run: sudo apt-get update && sudo apt-get -y install g++-${{matrix.gcc_version}}

    - name: Configure CMake
      run: cmake ./prj/cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TOOLCHAIN="g++-${{matrix.gcc_version}}" -DSIMD_TARGET="" -DSIMD_AVX512VNNI=ON -DSIMD_AVX512BF16=ON -DSIMD_AMXBF16=ON -DSIMD_TEST_FLAGS="-march=native"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --parallel$(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./Test "-r=.." -m=a -tt=$(nproc) "-ot=log_${{matrix.build_type}}.txt" -ts=10

  build_and_test_mingw:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MSYS
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git mingw-w64-ucrt-x86_64-gcc git make
        pacboy: toolchain:p cmake:p ninja:p

    - name: Host properties
      run: wmic cpu get /format:value

    - name: Configure CMake
      run: cmake ./prj/cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DSIMD_TARGET="x86_64" -DSIMD_GET_VERSION=OFF -DSIMD_TEST_FLAGS="-march=native"

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}} --parallel4

    - name: Test
      working-directory: build
      run: ./Test.exe "-r=.." -m=a -tt=-1 -ts=10
